<?xml version="1.0" encoding="UTF-8"?>
<definitions 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" 
	xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" 
	xmlns:tns="urn:AddOrderLine" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	targetNamespace="urn:AddOrderLine">
	<message name="AddOrderLineRequest">
		<part name="regnskab" type="xsd:string"/>
	</message>
	<message name="AddOrderLineResponse">
		<part name="return" type="xsd:string"/>
	</message>
	<portType name="AddOrderLinePortType">
		<operation name="AddOrderLine">
			<input message="tns:AddOrderLineRequest"/>
			<output message="tns:AddOrderLineResponse"/>
		</operation>
	</portType>
	<binding name="AddOrderLineBinding" type="tns:AddOrderLinePortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="AddOrderLine">
			<input>
				<soap:body use="encoded" namespace="urn:AddOrderLine" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:AddOrderLine" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="AddOrderLine">
		<port name="AddOrderLinePort" binding="tns:AddOrderLineBinding">
			<soap:address location="%SERVERURL%/addorderline.php"/>
		</port>
	</service>
</definitions>