<?xml version="1.0" encoding="UTF-8"?>
<definitions 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" 
	xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" 
	xmlns:tns="urn:Invoice" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	targetNamespace="urn:Invoice">
	<message name="InvoiceRequest">
		<part name="regnskab" type="xsd:string"/>
	</message>
	<message name="InvoiceResponse">
		<part name="return" type="xsd:string"/>
	</message>
	<portType name="InvoicePortType">
		<operation name="Invoice">
			<input message="tns:InvoiceRequest"/>
			<output message="tns:InvoiceResponse"/>
		</operation>
	</portType>
	<binding name="InvoiceBinding" type="tns:InvoicePortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="Invoice">
			<input>
				<soap:body use="encoded" namespace="urn:Invoice" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:Invoice" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="Invoice">
		<port name="InvoicePort" binding="tns:InvoiceBinding">
			<soap:address location="%SERVERURL%/invoice.php"/>	
		</port>
	</service>
</definitions>