<?xml version="1.0" encoding="UTF-8"?>
<definitions 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" 
	xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" 
	xmlns:tns="urn:Logoff" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	targetNamespace="urn:Logoff">
	<message name="LogoffRequest">
		<part name="regnskab" type="xsd:string"/>
	</message>
	<message name="LogoffResponse">
		<part name="return" type="xsd:string"/>
	</message>
	<portType name="WebservicePortType">
		<operation name="Logoff">
			<input message="tns:LogoffRequest"/>
			<output message="tns:LogoffResponse"/>
		</operation>
	</portType>
	<binding name="WebserviceBinding" type="tns:WebservicePortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="Logoff">
			<input>
				<soap:body use="encoded" namespace="urn:Logoff" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:Logoff" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="Webservice">
		<port name="WebservicePort" binding="tns:WebserviceBinding">
			<soap:address location="https://ssl.saldi.dk/finans/soapserver/logoff.php"/>
		</port>
	</service>
</definitions>