<?xml version="1.0" encoding="UTF-8"?>
<definitions 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" 
	xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" 
	xmlns:tns="urn:Singleupdate" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	targetNamespace="urn:Singleupdate">
	<message name="SingleupdateRequest">
		<part name="regnskab" type="xsd:string"/>
	</message>
	<message name="SingleupdateResponse">
		<part name="return" type="xsd:string"/>
	</message>
	<portType name="SingleupdatePortType">
		<operation name="Singleupdate">
			<input message="tns:SingleupdateRequest"/>
			<output message="tns:SingleupdateResponse"/>
		</operation>
	</portType>
	<binding name="SingleupdateBinding" type="tns:SingleupdatePortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="Singleupdate">
			<input>
				<soap:body use="encoded" namespace="urn:Singleupdate" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:Singleupdate" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="Singleupdate">
		<port name="SingleupdatePort" binding="tns:SingleupdateBinding">
			<soap:address location="%SERVERURL%/singleupdate.php"/>
		</port>
	</service>
</definitions>