<?php
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('10', 'D&aelig;kningsbidragsgivende aktiviteter', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1000', 'Oms&aelig;tning', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('10100', 'Varesalg Indland', 'D', '', '', 'S1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('10200', 'Varesalg EU', 'D', '', '', 'S1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('10300', 'Timesalg', 'D', '', '', 'S1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('10305', 'Fragt, ydet', 'D', '', '', 'S1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('10350', 'K&oslash;rsel indt&aelig;gt', 'D', '0', '0', 'S1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('10500', 'Diverse indt&aelig;gter', 'D', '0', '0', 'S1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('10600', 'Henvisningsprovision', 'D', '', '', 'S1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('10990', 'Oms&aelig;tning i alt', 'Z', '1000', '10990', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1200', 'Vareforbrug', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('12000', 'Varek&oslash;b - Danmark', 'D', '0', '0', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('12305', 'Fragt, modtaget', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('13000', 'Varek&oslash;b - EU', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('13500', 'Varek&oslash;b - &Oslash;vrige lande', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('13510', 'Konsulenter - fremmed', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('13600', 'Varelagerregulering', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('13700', 'Vareforbrug i alt', 'Z', '1200', '13700', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('13950', 'Vareomkostninger i alt', 'Z', '1200', '13950', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('13970', 'D&aelig;knings-bidrag (BruttoAvance)', 'Z', '1000', '13970', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14', 'Kapacitetsomkostninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1400', 'Repr&aelig;sentation omfattet af skattem&aelig;ssige begr&aelig;nsninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14000', 'Repr&aelig;sentation, restaurant', 'D', '0', '0', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14050', 'Vin, spiritus m.m.', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14100', 'Gaver & Blomster', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14150', 'Repr&aelig;sentation omfattet af skattem&aelig;ssige begr&aelig;nsninger i alt', 'Z', '1400', '14150', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1420', 'Repr&aelig;sentation ikke omfattet af skattem&aelig;ssige begr&aelig;nsninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14200', 'Rejseudgifter, hotel Danmark', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14250', 'Rejseudgifter, &oslash;vrige - Udland', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14270', 'Bus/Tog/Fly/F&aelig;rge billetter', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14280', 'Repr&aelig;sentation ikke omfattet af skattem&aelig;ssige begr&aelig;nsninger i alt', 'Z', '1420', '14280', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1440', '&Oslash;vrige salgsomkostninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14400', 'Taxak&oslash;rsel', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14420', 'Parkeringsomkostninger', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14450', 'Fragt', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14500', 'Annoncer & reklamer', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14600', 'Markedsf&oslash;rings omkostninger', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14700', 'Tidsskrifter', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14800', 'Aviser', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14810', 'Faglitteratur', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14890', 'Hensat tab p&aring; debitorer', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('14900', '&Oslash;vrige salgsomkostninger i alt', 'Z', '1420', '14900', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1500', 'Bildrift', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('15000', 'Diesel', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('15100', 'Forsikring', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('15110', 'V&aelig;gtafgift', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('15200', 'Reparation', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('15300', 'Falck', 'D', '0', '0', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('15400', 'Garage o.lign', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('15500', 'Leasing af bil', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('15950', 'Bildrift i alt', 'Z', '1500', '15950', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1600', 'Personaleomkostninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16000', 'Personaleomkostninger', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16100', 'Fort&aelig;ring (ved kursus)', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16110', 'Fort&aelig;ring (ved overtid)', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16200', 'Kursusudgifter- egne medarb.', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16300', 'PC Ordning - personale', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16400', 'Personaleomkostninger - &oslash;vrig i alt', 'Z', '1600', '16400', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1650', 'Personaleomkostninger - L&oslash;n', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16520', 'A-indkomst', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16521', 'L&oslash;ntilskud', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16525', 'Feriepenge', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16530', 'K&oslash;rselsgodtgrelse', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16540', 'ATP-bidrag', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16541', 'AER-bidrag', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16542', 'AES - bidrag', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16543', 'Arbejdsmiljafgift', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16544', 'Finanseringsbidrag og Kompensation', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16550', 'AM-bidrag l&oslash;nmodtager', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16551', 'Midlertidig Pension', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16560', 'Arbejdsmarkedsbidrag - Arbgiver', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16800', 'Personaleomkostninger- L&oslash;n I alt', 'Z', '1650', '16800', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('16900', 'Personaleomkostninger ialt', 'Z', '1600', '16900', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1700', 'Lokaleomkostninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('17000', 'Husleje & Varme', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('17010', 'Leje & Varmeindt&aelig;gt Lejer', 'D', '', '', 'S1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('17300', 'Elektricitet', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('17600', 'Rengring & Renovation', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('17610', 'Leje af hvidevarer', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('17700', 'Reperation & Vedligeholdelse af Lokaler', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('17950', 'Lokaleomkostninger i Alt', 'Z', '1700', '17950', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('1800', 'Administrations Omkostninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18000', 'Sm&aring; anskaffelser under 8.600,-', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18060', 'Sm&aring; anskaffelser EDB', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18070', 'EDB Udgifter', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18080', 'Reperation & Vedligeholdelse af udstyr', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18100', 'Kontorartikler', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18200', 'Fasttelefoni', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18205', 'Telefonpasning', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18210', 'ADSL forbindelser', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18230', 'Telefon - Mobil', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18250', 'Kontingenter med Moms', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18260', 'Kontingenter Uden Moms', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18300', 'Forsikringer', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18350', 'Porto', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18351', 'Pakke Porto', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18400', 'Revision', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18420', 'Advokat', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18430', 'Praktikanter(Vikarer)', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18500', 'Gebyrer-abonnementer', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18900', 'Kassedifference', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18910', 'Diverse Med Moms', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18920', 'Diverse Uden Moms', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18940', 'AdministrationsOmkostninger i alt', 'Z', '17990', '18940', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('18960', 'Kapacitetsomkostning i alt', 'Z', '13990', '18960', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('24', 'Af - og nedskrivninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('2400', 'Afskrivninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('24100', 'Afskrivning Biler', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('24200', 'Afskrivning Telefonanl&aelig;g', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('24300', 'Afskrivning Inventar', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('24400', 'Afskrivning GoodWill', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('24450', 'Tab af salg af inventar', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('24500', 'Afskrivninger i Alt', 'Z', '2400', '24500', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26', 'Finansielle poster', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('2600', 'Finansielle indt&aelig;gter', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26050', 'Renteindt&aelig;gter - Bank', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26100', 'Renteindt&aelig;gter - Giro', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26150', 'Renteindt&aelig;gter - Debitorer', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26200', 'Finansielle indt&aelig;gter i alt', 'Z', '2600', '26200', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('2660', 'Finansielle omkostninger', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26650', 'Renteudgifter - Bank', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26700', 'Renteudgifter - Giro', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26750', 'Renteudgifter - Kreditorer', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26800', 'Renteudgifter - Andet', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26810', 'Diverse bank/giro gebyrer', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26850', 'Afsat udbytte', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('26900', 'Finansielle Omkostninger i alt', 'Z', '2660', '26900', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('27000', 'Ekstarordin&aelig;re poster', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('27200', 'Ekstraordin&aelig;re indt&aelig;gter', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('27300', 'Ekstraordin&aelig;re udgifter', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('27400', 'Ekstraordin&aelig;re poster i alt', 'Z', '27000', '27400', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('2800', 'Selskabsskat', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('28100', 'Skat af &aring;rets resultat', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('28200', 'Regulering tidligere &aring;r', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('28300', 'Regulering af eventualskat', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('28400', 'Selskabsskat i Alt', 'Z', '2800', '28400', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('28500', '&Aring;rets resultat', 'Z', '1000', '28500', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('28510', 'Nulstil drift - DUMMY', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('28512', 'Overf&oslash;r resultat', 'Z', '1', '28510', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('30', 'Aktiver', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('3000', 'Oms&aelig;tningsaktiver', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('30100', 'KasseBeholding', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('30200', 'Giro', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('30300', 'Bank', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('30400', 'Forudbetalte omkostninger', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('30500', 'Udl&aelig;g', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('30600', 'Igangv&aelig;rende arbejder', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('30700', 'Oms&aelig;tningsaktiver ialt', 'Z', '3000', '30700', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('3300', 'Varelager', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33100', 'Varelager Software Primo', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33200', 'Varelager Software tilgang', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33300', 'Varelager Software Afgang', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33400', 'Varelager Software Ultimo', 'Z', '3300', '33400', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33500', 'Varelager Hardware Primo', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33600', 'Varelager Hardware Tilgang', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33700', 'Varelager Hardware Afgang', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33750', 'Intern k&oslash;b', 'D', '', '', 'K1', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33800', 'Varelager Hardware Ultimo', 'Z', '33500', '33800', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('33900', 'Varelager i alt', 'Z', '3300', '33900', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('3500', 'Anl&aelig;gsaktiver', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35050', 'Sm&aring;anskaffelser', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35100', 'Telefonanl&aelig;g', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35150', 'Afgang driftmidler', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35250', 'Inventar', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35251', 'Afskrivninger, inventar og biler', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35300', 'Debitorer samlekonto', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35301', 'Hensat debitorer', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35550', 'Billeasing', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35600', 'Dispositum husleje', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35700', 'Goodwill', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35800', 'Indretning, lejede lokaler', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35801', 'Afskrivning indretn. af lejede lokaler', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35900', 'Anl&aelig;gsaktiver ialt', 'Z', '3500', '35800', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('35950', 'Aktiver ialt', 'Z', '3000', '35950', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('40', 'Passiver', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('4000', 'Egenkapital', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('40100', 'Selskabskapital', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('40150', 'Overkurs', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('40200', 'Overfrte resultater', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('40400', 'Egenkapital ialt', 'Z', '4000', '40400', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('4500', 'Kortfristet g&aelig;ld', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45100', 'Skyldig ATP-bidrag', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45200', 'Indeholdt A-skat', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45300', 'Betalt A-skat', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45400', 'Indeholdt AMB l&oslash;nmodtager', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45500', 'Indeholdt pension', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45600', 'Betalt AMB l&oslash;nmodtager', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45700', 'Betalt pension', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45800', 'Indeholdt AMB arbejdsgiver', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45900', 'Betalt AMB arbejdsgiver', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45950', 'FFE - lovpligtig arbejdskadeforsikring', 'D', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('45960', 'Hensat til feriepenge', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('50100', 'Varekreditorer', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('50150', 'F&oslash;lgesedler (ej faktureret varek&oslash;b)', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('50200', 'Skyldige omkostninger', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('50260', 'Bill&aring;n', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('50300', 'Selskabsskat', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('50350', 'Eventualskat', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('50400', 'Kortfristet g&aelig;ld ialt', 'Z', '4500', '50400', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('60100', 'Mellemregning Holding', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('8000', 'Moms & skyldige afgifter', 'H', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('80100', 'Udg&aring;ende moms', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('80150', 'EU moms', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('80200', 'Indg&aring;ende moms', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('80300', 'El-afgift', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('80400', 'CO2-afgift', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('80500', 'Momsafregning', 'S', '', '', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('80600', 'Moms og skyldige afgifter i alt', 'Z', '8000', '80600', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('80990', 'Passiver ialt', 'Z', '4000', '80990', '', '1')");
db_modify("INSERT INTO kontoplan (kontonr, beskrivelse, kontotype, fra_kto, til_kto, moms, regnskabsaar) values ('90000', 'Balance', 'Z', '3000', '80990', '', '1')");

db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Debitorer', 'D', '1', 'DG', '1', '35300', 'DKK', '', '', '', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Indg&aring;nde moms (K&oslash;bsmoms) 25%', 'K', '1', 'KM', '80200', '25', '', '', '', '', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Indg&aring;nde moms (K&oslash;bsmoms) 6,25%', 'K', '2', 'KM', '80200', '6.25', '', '', '', '', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Danske kreditorer', 'K', '1', 'KG', '1', '50100', 'DKK', '', '', '', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('&Oslash;vrige kreditorer', 'K', '2', 'KG', '1', '50100', 'EUR', '', '', '', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Udg&aring;ende moms (Salgsmoms) 25%', 'S', '1', 'SM', '80100', '25', '', '', '', '', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Danske kroner', '', '1', 'VK', 'DKK', '100', '', '', '', '', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Euro', '', '2', 'VK', 'EUR', '750', '', '', '', '', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('test', '', '1', 'PK', '', '', '', '', '', '', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Fragt', '', '2', 'VG', '', '', '12305', '10305', '80200', '80100', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Handelsvarer', '', '1', 'VG', '33600', '33700', '12000', '10100', '80200', '80100', '', 'on')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Ydelser', '', '3', 'VG', '', '', '13510', '10300', '80200', '80100', '', '')");
db_modify("INSERT INTO grupper (beskrivelse, kode, kodenr, art, box1, box2, box3, box4, box5, box6, box7, box8) values ('Output', '', '1', 'PV', '/usr/bin/lpr', '/usr/bin/ps2pdf', '', '', '', '', '', '')");

?>
